from pathlib import Path

APP_NAME = "PC Connect"
VERSION = "4.0.1"
PROTOCOL_VERSION = 4
DISCOVERY_PORT = 5001
CHAT_PORT = 5002
BUFFER_SIZE = 65536
ANNOUNCE_INTERVAL = 2
STALE_SECONDS = 8
CONNECT_TIMEOUT = 5
MAX_PACKET_SIZE = 1024 * 1024
MAX_HISTORY_ENTRIES = 1000
MAX_CHAT_LENGTH = 10000

DATA_DIR = Path.home() / ".pc-connect"
RECEIVED_FILES_DIR = DATA_DIR / "received_files"
RECEIVED_FOLDERS_DIR = DATA_DIR / "received_folders"
HISTORY_FILE = DATA_DIR / "transfer_history.json"
SETTINGS_FILE = DATA_DIR / "settings.json"
